import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// export async function getStaticPaths() {
//   const res = await fetch("https://xoafterglow.com/api/blogs/slugs", {
//     headers: {
//       "XO-API-KEY": process.env.XO_API_KEY ? process.env.XO_API_KEY : "",
//     },
//   });
//   const jsonRes = await res.json();
//   const paths = jsonRes.map((slug: string) => ({
//     params: { slug },
//   }));

//   return {
//     paths,
//     fallback: false,
//   };
// }

// export const getStaticProps: GetStaticProps = async context => {
//   const slug = context.params.slug;
//   return {
//     props: {},
//     revalidate: 60 * 60,
//   };
// };

export default Home;
